dist: "xenial"
language: node_js
node_js:
  - "12"

branches:
  only:
  - master

services:
  - postgresql
addons:
  postgresql: "10"

env:
  global:
    - VULCYN_TEST_PG_HOST="localhost"
    - VULCYN_TEST_PG_USER="postgres"
    - VULCYN_TEST_PG_PASSWORD=""
    - VULCYN_TEST_PG_DATABASE="travis_ci_test"

before_script:
  - psql -c "CREATE DATABASE ${VULCYN_TEST_PG_DATABASE};" -U postgres
