on: [ "push" ]
jobs:
  test:
    runs-on: ubuntu-latest
    container: node:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: VULCYN_TEST_PG_PASSWORD=1234 VULCYN_TEST_PG_HOST=postgres VULCYN_TEST_PG_PORT="${{ job.services.postgres.ports['5432'] }}" yarn run test
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432/tcp
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "1234"
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5